name: Push to DockerHub

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  workflow_call:

env:
    image_tag_suffix: ${{ github.ref != 'refs/heads/main' && '-beta' || '' }}
 
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/sanduba-payment-api
          tags: |
            type=raw,value={{date 'YYYY.MM'}}{{$image_tag_suffix}}
            type=raw,value=latest{{$image_tag_suffix}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./src/Sanduba.Payment.MercadoPago/
          file: ./src/Sanduba.Payment.MercadoPago/Sanduba.Cloud.Function.MercadoPago/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}