name: Push to DockerHub & Azure

on: 
  push:
    branches: ['main', 'develop']
    paths-ignore:
      - '**/*.md'
      - '.github/*.*'
  workflow_dispatch:
 
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set conditional suffix for latest tag
        id: set-conditional-suffix
        run: |
          if [[ ${{ github.ref }} == refs/heads/main ]]; then
            echo "TAG_SUFFIX=" >> $GITHUB_ENV
          else
            echo "TAG_SUFFIX=-beta" >> $GITHUB_ENV
          fi

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/sanduba-payment-api
          tags: |
            type=raw,value={{date 'YYYY.MM'}}${{ env.TAG_SUFFIX }}
            type=raw,value=latest${{ env.TAG_SUFFIX }} 

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./src/Sanduba.Payment.MercadoPago/
          file: ./src/Sanduba.Payment.MercadoPago/Sanduba.Cloud.Function.MercadoPago/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}


      - name: Log in to Azure CLI
        uses: Azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_SERVICE_PRINCIPAL_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_SERVICE_PRINCIPAL_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SERVICE_PRINCIPAL_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_SERVICE_PRINCIPAL_TENANT_ID }}"}'

      - name: 'Run Azure Functions Container Action'
        uses: Azure/functions-container-action@v1
        with:
          app-name: 'sanduba-payment-function'
          image: 'index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/sanduba-payment-api:latest${{ env.TAG_SUFFIX }}'